[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
runOnSave = false
maxUploadSize = 500
disconnectedSessionTTL = 3600
fileWatcherType = "none"

[theme]
primaryColor = "#06b6d4"
backgroundColor = "#000000"
secondaryBackgroundColor = "#000000"
textColor = "#ffffff"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s [%(levelname)s] %(message)s"

[browser]
gatherUsageStats = false

